baseURL = 'http://example.org/'
languageCode = 'de'
title = 'VM_contact'
theme = 'blowfish'
#publishDir = 'docs'

defaultContentLanguage = "de"
[languages]
  [languages.de]
    languageName = "Deutsch"
    weight = 1
  [languages.fr]
    languageName = "Français"
    weight = 2
